name: Build SniperApp APK

on:
  # Cette ligne permet de lancer la compilation manuellement
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Récupérer votre code depuis le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2: Mettre en place Java (nécessaire pour Gradle)
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # Étape 3: Lancer la compilation avec Buildozer
    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        workdir: 
        buildozer_version: master

    # Étape 4: Mettre en ligne l'APK une fois qu'il est prêt
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sniperapp-apk
        path: bin/*.apk
